matrix:
        include:
                - os: linux
                  language: c
                  env:
                          - WITH_CRYPTO=MBEDTLS
                            WITH_SYSTEM_DEPENDENCIES=OFF
                            ENABLE_TESTING=ON
                            GENERATOR="Unix Makefiles"
                  addons:
                          apt:
                                  packages:
                                          - valgrind
                                          - lcov
                                          - libssl-dev
                  script:
                          - ./scripts/ci/build.sh
                - os: linux
                  language: c
                  env:
                          - WITH_CRYPTO=OPENSSL
                            WITH_SYSTEM_DEPENDENCIES=ON
                            ENABLE_TESTING=ON
                            GENERATOR="Unix Makefiles"

                  addons:
                          apt:
                                  packages:
                                          - valgrind
                                          - lcov
                                          - libssl-dev
                  script:
                          - ./scripts/ci/build.sh
                - os: windows
                  language: c
                  env:
                          - WITH_CRYPTO=OPENSSL
                            WITH_SYSTEM_DEPENDENCIES=ON
                            GENERATOR="Visual Studio 15 2017 Win64"
                  script:
                          - choco install openssl
                          - ./scripts/ci/build.sh
