language: c
env:
        - WITH_MBEDTLS=ON
          WITH_SYSTEM_DEPENDENCIES=OFF
          ENABLE_TESTING=ON
        - WITH_OPENSSL=ON
          WITH_SYSTEM_DEPENDENCIES=ON
          ENABLE_TESTING=ON
addons:
        apt:
                packages:
                        - valgrind
                        - lcov
                        - libssl-dev
script:
        - cmake
          -DCMAKE_INSTALL_PREFIX=./build/install
          -DWITH_MBEDTLS=$WITH_MBEDTLS
          -DWITH_OPENSSL=$WITH_OPENSSL
          -DWITH_SYSTEM_DEPENDENCIES=$WITH_SYSTEM_DEPENDENCIES
          -DENABLE_TESTING=$ENABLE_TESTING .
        - cmake --build . --target install
